### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by adam-gregory** [imrefazekas/connect-rest#32]
/myproject/node_modules/connect-rest/lib/rest-services.js:3
let url = require('url')
^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/app.js:10:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"

**Comment by imrefazekas** [comment]
Dear Adam,
Yes, "from version 2.0.0 connect-rest requires NodeJS 4.0.0 or higher". 
Please update your node or use an older version of the lib.
Cheers

**Comment by adam-gregory** [comment]
That seems to have fixed it. Thank you
